[profile.default]
src = "src"
test = "test"
libs = ["node_modules"]
via_ir = true
optimizer = true
solc_version = '0.8.28'
optimizer_runs = 200
dynamic_test_linking = true
fs_permissions = [
  { access = "readwrite", path = "./addresses" },
  { access = "readwrite", path = "./addresses/dev" },
  { access = "read", path = "./package.json" },
  { access = "readwrite", path = "./deterministicConfig" },
  { access = "read", path = "../shared-contracts/chainConfigs" },
  { access = "read", path = "../shared-contracts/deterministicConfig" }
]
remappings = [
  "lib/=lib/",
  "@uniswap/v4-core/=node_modules/@uniswap/v4-core/",
  "permit2/=lib/permit2/src/"
]

[profile.ci.fuzz]
runs = 100

[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
zora = "https://rpc.zora.energy"